name: 飞网
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 取出代码
        uses: actions/checkout@v2
      - name: 飞网自动化
        uses: ./
        with:
          authkey: ${{ secrets.GMZTA_AUTHKEY }}
      - name: 验证飞网
        run:
          gmzta info 
